;设置规则标志位
ruleset=DIRECT,https://raw.githubusercontent.com/BGDRr/HELLO/main/rule/WIFI.yaml
ruleset=PT PROXY,https://raw.githubusercontent.com/BGDRr/HELLO/main/rule/PT_PROXY.yaml
ruleset=PT DIRECT,https://raw.githubusercontent.com/BGDRr/HELLO/main/rule/PT.yaml
ruleset=Speedtest,https://raw.githubusercontent.com/BGDRr/HELLO/main/rule/Speedtest.yaml
ruleset=OpenAI,https://raw.githubusercontent.com/BGDRr/HELLO/main/rule/OpenAI.yaml
ruleset=Emby,https://raw.githubusercontent.com/BGDRr/HELLO/main/rule/emby.yaml
ruleset=Bing,https://raw.githubusercontent.com/BGDRr/HELLO/main/rule/Bing.yaml
ruleset=Youtube,https://raw.githubusercontent.com/BGDRr/HELLO/main/rule/YouTube.yaml
ruleset=Google,https://github.com/BGDRr/HELLO/blob/main/rule/Google.yaml
ruleset=Instagram,https://raw.githubusercontent.com/BGDRr/HELLO/main/rule/Instagram.yaml
ruleset=Mainland,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=Mainland,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=Mainland,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=Mainland,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=OneDrive,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Microsoft,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=Apple,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=Telegram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list
ruleset=AppleMusic,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleMusic/AppleMusic.list
ruleset=Game,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=Game,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=Game,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=Game,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=Game,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=Netflix,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=AppleTV+,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/AppleTV/AppleTV.list
ruleset=Disney+,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
ruleset=HBO,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/myTVSUPER/myTVSUPER.list
ruleset=HBO,https://raw.githubusercontent.com/BGDRr/HELLO/main/rule/HBOHK.yaml
ruleset=HBO,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PCCW/PCCW.list
ruleset=HBO,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBOAsia/HBOAsia.list
ruleset=HBO,https://raw.githubusercontent.com/BGDRr/HELLO/main/rule/HBO.yaml
ruleset=HBO,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Espn/Espn.list
ruleset=HBO,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Fox/Fox.list
ruleset=HBO,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ParamountPlus/ParamountPlus.list
ruleset=HBO,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Peacock/Peacock.list
ruleset=HBO,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HuluUSA/HuluUSA.list
ruleset=HBO,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DiscoveryPlus/DiscoveryPlus.list
ruleset=HBO,https://raw.githubusercontent.com/xuanranran/Clash/main/Clash/MAX.list
ruleset=Bilibili,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=Bilibili,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=Mainland,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=PROXY,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=PROXY,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
;ruleset=Mainland,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=Mainland,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=Mainland,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=Mainland,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=Mainland,[]GEOIP,LAN
ruleset=Mainland,[]GEOIP,CN
ruleset=FINAL,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=SELECT`select`.*
custom_proxy_group=PROXY`select`[]DIRECT`[]SELECT`[]HK`[]AutoHK`[]SG`[]AutoSG`[]AutoTW`[]AutoJP`[]AutoUS`[]AutoKR
custom_proxy_group=Mainland`select`[]DIRECT`[]PROXY`[]HK`[]AutoHK`[]SG`[]AutoSG`[]AutoTW`[]AutoJP`[]AutoUS`[]AutoKR
custom_proxy_group=FINAL`select`[]DIRECT`[]PROXY`[]HK`[]AutoHK`[]SG`[]AutoSG`[]AutoTW`[]AutoJP`[]AutoUS`[]AutoKR
custom_proxy_group=PT PROXY`select`[]DIRECT`[]PROXY`[]HK`[]AutoHK`[]SG`[]AutoSG`[]AutoTW`[]AutoJP`[]AutoUS`[]AutoKR
custom_proxy_group=PT DIRECT`select`[]DIRECT`[]PROXY`[]HK`[]AutoHK`[]SG`[]AutoSG`[]AutoTW`[]AutoJP`[]AutoUS`[]AutoKR
custom_proxy_group=Telegram`select`[]DIRECT`[]PROXY`[]HK`[]AutoHK`[]SG`[]AutoSG`[]AutoTW`[]AutoJP`[]AutoUS`[]AutoKR
custom_proxy_group=Instagram`select`[]DIRECT`[]PROXY`[]HK`[]AutoHK`[]SG`[]AutoSG`[]AutoTW`[]AutoJP`[]AutoUS`[]AutoKR
custom_proxy_group=OpenAI`select`[]DIRECT`[]PROXY`[]HK`[]AutoHK`[]SG`[]AutoSG`[]AutoTW`[]AutoJP`[]AutoUS`[]AutoKR
custom_proxy_group=Bing`select`[]DIRECT`[]PROXY`[]HK`[]AutoHK`[]SG`[]AutoSG`[]AutoTW`[]AutoJP`[]AutoUS`[]AutoKR
custom_proxy_group=Youtube`select`[]DIRECT`[]PROXY`[]HK`[]AutoHK`[]SG`[]AutoSG`[]AutoTW`[]AutoJP`[]AutoUS`[]AutoKR
custom_proxy_group=Netflix`select`[]DIRECT`[]PROXY`[]HK`[]AutoHK`[]SG`[]AutoSG`[]AutoTW`[]AutoJP`[]AutoUS`[]AutoKR
custom_proxy_group=Disney+`select`[]DIRECT`[]PROXY`[]HK`[]AutoHK`[]SG`[]AutoSG`[]AutoTW`[]AutoJP`[]AutoUS`[]AutoKR
custom_proxy_group=HBO`select`[]DIRECT`[]PROXY`[]HK`[]AutoHK`[]SG`[]AutoSG`[]AutoTW`[]AutoJP`[]AutoUS`[]AutoKR
custom_proxy_group=AppleTV+`select`[]DIRECT`[]PROXY`[]HK`[]AutoHK`[]SG`[]AutoSG`[]AutoTW`[]AutoJP`[]AutoUS`[]AutoKR
custom_proxy_group=Bilibili`select`[]DIRECT`[]PROXY`[]HK`[]AutoHK`[]SG`[]AutoSG`[]AutoTW`[]AutoJP`[]AutoUS`[]AutoKR
custom_proxy_group=Emby`select`[]DIRECT`[]PROXY`[]HK`[]AutoHK`[]SG`[]AutoSG`[]AutoTW`[]AutoJP`[]AutoUS`[]AutoKR
custom_proxy_group=Speedtest`select`[]DIRECT`[]PROXY`[]HK`[]AutoHK`[]SG`[]AutoSG`[]AutoTW`[]AutoJP`[]AutoUS`[]AutoKR
custom_proxy_group=Microsoft`select`[]DIRECT`[]PROXY`[]HK`[]AutoHK`[]SG`[]AutoSG`[]AutoTW`[]AutoJP`[]AutoUS`[]AutoKR
custom_proxy_group=OneDrive`select`[]DIRECT`[]PROXY`[]HK`[]AutoHK`[]SG`[]AutoSG`[]AutoTW`[]AutoJP`[]AutoUS`[]AutoKR
custom_proxy_group=Apple`select`[]DIRECT`[]PROXY`[]HK`[]AutoHK`[]SG`[]AutoSG`[]AutoTW`[]AutoJP`[]AutoUS`[]AutoKR
custom_proxy_group=AppleMusic`select`[]DIRECT`[]PROXY`[]HK`[]AutoHK`[]SG`[]AutoSG`[]AutoTW`[]AutoJP`[]AutoUS`[]AutoKR
custom_proxy_group=Game`select`[]DIRECT`[]PROXY`[]HK`[]AutoHK`[]SG`[]AutoSG`[]AutoTW`[]AutoJP`[]AutoUS`[]AutoKR
custom_proxy_group=Spotify`select`[]DIRECT`[]PROXY`[]HK`[]AutoHK`[]SG`[]AutoSG`[]AutoTW`[]AutoJP`[]AutoUS`[]AutoKR
custom_proxy_group=HK`select`(港|HK|Hong Kong)
custom_proxy_group=SG`select`(新加坡|坡|狮城|SG|Singapore)
custom_proxy_group=AutoHK`url-test`(港|HK|Hong Kong)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=AutoSG`url-test`(新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=AutoJP`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=AutoUS`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=AutoTW`url-test`(台|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=AutoKR`url-test`(KR|Korea|KOR|首尔|韩|韓)`http://www.gstatic.com/generate_204`300,,50
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
